const i18n = {
  en: {
    signUp: "SIGN UP",
    login: "LOG IN",
    logout: "LOG OUT",
    calendar: "CALENDAR",
    profile: "PROFILE",
    allSeries: "ALL SERIES",
    reviews: "REVIEWS",
    allVolumes: "ALL VOLUMES",
    postReview: "Your review",
    rating: "Rating : ",
    post: "Post",
    comment: "Comment",
    editProfile: "Edit Profile",
    seeNsfw: "I want to see NSFW content",
    yourReviews: "YOUR REVIEWS",
    yourFavorites: "YOUR FAVORITES",
    uploadIm: "Upload an image:",
    username: "Username:",
    email: "Email:",
    password: "Password:",
    edit: "Edit",
    retProf: "Return to Profile",
    reviewsOf: "'S REVIEWS",
    favsOf: "'S FAVORITES",
    release: "UPCOMING RELEASES",
    discover: "DISCOVER NEW SERIES",
  },
  fr: {
    signUp: "Créer un Compte",
    login: "Se Connecter",
    logout: "Se déconnecter",
    calendar: "CALENDRIER",
    profile: "PROFIL",
    allSeries: "TOUTES LES SAGAS",
    reviews: "COMMENTAIRES",
    allVolumes: "TOUS LES VOLUMES",
    postReview: "Ajoutez votre propre commentaire !",
    rating: "Note : ",
    post: "Envoyer",
    comment: "Commentaire",
    editProfile: "Modifier mon Profil",
    seeNsfw: "Je veux voir le contenu 18+",
    yourReviews: "VOS COMMENTAIRES",
    yourFavorites: "VOS FAVORIS",
    uploadIm: "Télécharger une image:",
    username: "Pseudo:",
    email: "Email:",
    password: "Mot de passe:",
    edit: "Modifier",
    retProf: "Retourner au Profil",
    reviewsOf: "COMMENTAIRES DE ",
    favsOf: "FAVORIS DE ",
    release: "SORTIES PROCHAINES",
    discover: "DECOUVREZ DE NOUVELLES SAGAS",
  },
  es: {
    signUp: "REGISTRARSE",
    login: "INICIAR SESIÓN",
    logout: "CERRAR SESIÓN ",
    calendar: "CALENDARIO",
    profile: "PERFIL",
    allSeries: "SERIES",
    reviews: "RESEÑAS",
    allVolumes: "TODOS LOS TOMOS",
    postReview: "TUS RESEÑAS",
    rating: "Valoración :",
    post: "Publicar",
    comment: "Comentario",
    editProfile: "Modificar mi Perfil",
    seeNsfw: "Quiero ver el contenido 18+",
    yourReviews: "TUS RESEÑAS",
    yourFavorites: "TUS FAVORITOS",
    uploadIm: "Subir una imagen:",
    username: "Usuario:",
    email: "Email",
    password: "Contraseña:",
    edit: "Editar",
    retProf: "Volver al Perfil",
    reviewsOf: "RESEÑAS DE ",
    favsOf: "FAVORITOS DE ",
    release: "PRÓXIMAS PUBLICACIONES",
    discover: "DESCUBRIMIENTO",
  },
};

export default i18n;
